branches:
  only:
    - master

before_script:
  - sudo rabbitmqctl add_vhost /chef
  - sudo rabbitmqctl add_user chef testing
  - sudo rabbitmqctl set_permissions -p /chef chef ".*" ".*" ".*"
  - echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
  - sudo mkdir -p /etc/apt/trusted.gpg.d
  - sudo gpg --fetch-key http://apt.opscode.com/packages@opscode.com.gpg.key
  - sudo gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
  - gem install chef-server chef-server-api chef-server chef-solr
  - sudo mkdir -p /etc/chef
  - curl "https://raw.github.com/gist/1724769/1e79401b4b42faa7d47dfd7e33e8f5543d201381/server.rb" | sudo tee /etc/chef/server.rb
  - sudo nohup chef-solr-indexer &
  - sudo nohup chef-solr &
  - sudo nohup chef-server -N -e production &

language: ruby
rvm:
#  - 1.8.7
  - 1.9.2
#  - jruby-18mode
#  - rbx-18mode
