branches:
  only:
    - master

before_script:
  - echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
  - sudo mkdir -p /etc/apt/trusted.gpg.d
  - sudo gpg --fetch-key http://apt.opscode.com/packages@opscode.com.gpg.key
  - sudo gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null
  - sudo apt-get update
  - echo "chef chef/chef_server_url string http://localhost:4040" | sudo debconf-set-selections && sudo apt-get install chef
  - echo "chef-solr chef-solr/amqp_pass string chef" | sudo debconf-set-selections && sudo apt-get install chef-server-api chef-expander

language: ruby
rvm:
#  - 1.8.7
  - 1.9.2
#  - jruby-18mode
#  - rbx-18mode
